name: Tests

on:
  push:
    branches:
      - main
  pull_request: {}

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-docker:
    name: Test STAC App Docker Image
    runs-on: ubuntu-latest

    services:
      postgres:
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgis
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDATABASE: postgis
        image: ghcr.io/stac-utils/pgstac:v0.9.8
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6.2.0
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build Docker Image
        id: push
        uses: docker/build-push-action@v7.3.0
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}

      - name: Run Test
        run: |
          make docker-run \
            DOCKER_RUN_IMAGE="${{ steps.meta.outputs.tags }}" \
            DOCKER_RUN_NETWORK="${{ job.container.network }}"
          docker ps
          make docker-test \
            DOCKER_TEST_NETWORK="${{ job.container.network }}"
